### ISSUE TITLE
[Discussion/Suggestion] Better alternative instead of sed to change files

### ISSUE THREAD

**Issue by pagdot** [ironicbadger/ansible-role-proxmox-nag-removal#9]
*ansible.builtin.shell* + `sed` is a little bit a hack when using ansible.

A better way would be to use *ansible.builtin.replace* because it should be similar to `sed`, but included in ansible and would properly report if there were changes.

An alternative way, brought up by @FuzzyMistborn on Discord would be to use a diff file and `patch` like discussed here: https://github.com/foundObjects/pve-nag-buster/issues/3

This would make it easier to work with (no hard-to-read regex), but I haven't seen an ansible module to patch a file. This would require Copying the diff and then executing `patch`.

I'm willing to add a patch to implement either of the two in a PR :)

~I'd like to wait for the completion of #8 first to prevent issues or doing it twice~ (Didn't see that is was already accepted)

**Comment by FuzzyMistborn** [comment]
There also is ansible.builtin.lineinfile which I think could be used.

And yes, Alex merged that PR while live podcasting.  Such skill. :-)

**Comment by pagdot** [comment]
Do we need to replace the whole line?

**Comment by FuzzyMistborn** [comment]
I'm fairly certain the entire line currently is replaced. That may not always be true.

**Comment by pagdot** [comment]
At the moment it replaces only a part:

```diff
		success: function(response, opts) {
		    let res = response.result;
		    if (res === null || res === undefined || !res || res
-			.data.status.toLowerCase() !== 'active') {
+			.false) {
			Ext.Msg.show({
			    title: gettext('No valid subscription'),
			    icon: Ext.Msg.WARNING,
			    message: Proxmox.Utils.getNoSubKeyHtml(res.data.url),
			    buttons: Ext.Msg.OK,
			    callback: function(btn) {
				if (btn !== 'ok') {
				    return;
				}
				orig_cmd();
			    },
			});
		    } else {
			orig_cmd();
		    }
		},
```
I don't know hot the `.false` is handled. Because that means `res.false`

**Comment by sumnerboy12** [comment]
I just ran this latest version of the role and now my `proxmoxlib.js` looks like;

```
false/false/false false2false.false5false-false6false
falseEfalsexfalsetfalse.falsenfalsesfalse(false'falsePfalserfalseofalsexfalsemfalseofalsexfalse'false)false;false
falseEfalsexfalsetfalse.falsenfalsesfalse(false'falsePfalserfalseofalsexfalsemfalseofalsexfalse.falseSfalseefalsetfalseufalsepfalse'false)false;false
false
falseifalseffalse false(false!falseEfalsexfalsetfalse.falseifalsesfalseDfalseefalseffalseifalsenfalseefalsedfalse(falsePfalserfalseofalsexfalsemfalseofalsexfalse.falseSfalseefalsetfalseufalsepfalse.falseafalseufalsetfalsehfalse_fa$
false false false false falsetfalsehfalserfalseofalsewfalse false"falsePfalserfalseofalsexfalsemfalseofalsexfalse falselfalseifalsebfalserfalseafalserfalseyfalse falsenfalseofalsetfalse falseifalsenfalseifalsetfalseifalseafalselfa$
false}false
false
```

Any ideas what might have gone wrong here?!

**Comment by ironicbadger** [comment]
No clue. I'll do my best to take a look tonight but it might be this week before I get to it.

**Comment by pagdot** [comment]
Found the issue and fixed it. Forgot to escape something... Swapped it with the working line from my own playbook. Don't know why there was a difference in the first place. I guess I had the issue, but forgot to fix it here too...

**Comment by RealOrangeOne** [comment]
The referenced project does a very simple find/replace on a fixed string, rather than a regex. Any reason not to just do something similar? 

https://github.com/foundObjects/pve-nag-buster/blob/master/pve-nag-buster.sh#L30

**Comment by pagdot** [comment]
Ansibles [replace](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/replace_module.html) seems to only support regex. My variant is pretty much a searchstring escaped so it can be used as regex
